### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by camsjams** [rafde/PrioritizedSubPub#1]
Hi,

Great plugin - it seems like the documentation on the readme doesn't match the actual code, as the doc says `EventPriorityEmitter` whereas the code actually expects `PrioritizedSubPub`.

Thanks Raf!

~ Cameron

**Comment by rafde** [comment]
Yeah. Take a look at develop branch. I have a lot of work I also have not committed that I will when I get back from vacation.

**Comment by camsjams** [comment]
I see - when is your expected launch date? I am using the current master build and like it a lot.

**Comment by rafde** [comment]
I'll try to get something finished by this weekend. No one was using it before so I didn't have a deadline.

**Comment by rafde** [comment]
Ah right, so I updated the docs for the read me and the site. you can check it out if you like.
Closing issue.

**Comment by rafde** [comment]
I realized that I am missing some stuff that are considered requirements in the documentation, I will update them later tonight.

**Comment by rafde** [comment]
OK. I think I have the README.md done. Hopefully it all makes sense.

**Comment by rafde** [comment]
@camsjams : OK. I think I have the README.md done. Hopefully it all makes sense. Feel free to point out my incoherence.

**Comment by camsjams** [comment]
Wow looks great! Let me pour through it a little more, but I will close out this issue
