### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by camsjams** [rafde/PrioritizedSubPub#14]
When calling `PrioritizedSubPub`, IE8 will throw errors `Function expected` and when you log `PrioritizedSubPub` directly, such as in the console, it is referenced in IE8 as nothing more than:

```
[object] { }
```

**Comment by camsjams** [comment]
Ah I found. In the form of:
`var  PrioritizedSubPub = PrioritizedSubPub || {};`

When doing so, IE8 seems to destroy the variable and set it to `{}`. Nice quirk.

**Comment by rafde** [comment]
That's a weird one.
I think a safer check would look like

```
window.PrioritizedSubPub = window.PrioritizedSubPub || function () {};
```

Since `window` is better than using an assumed global that could be `undefined`. Also, it's a function with static properties.

BTW, I am thinking of renaming this to something catchy. If you have a suggestion, feel free.

**Comment by camsjams** [comment]
Yoke JS?

`put a yoke on (a pair of animals); couple or attach with or to a yoke.`

I started one a while but can donate the name to you:
https://github.com/camsjams/yokejs

**Comment by rafde** [comment]
I also saw this definition

> [something that causes people to be treated cruelly and unfairly especially by taking away their freedom](http://www.merriam-webster.com/dictionary/yoke)

It reminds me of `yokel`
