### ISSUE TITLE
Change _debugLog a bit?

### ISSUE THREAD

**Issue by camsjams** [rafde/PrioritizedSubPub#2]
Perhaps you can change private function `_debugLog` to this so that the it works better in IE8 AND arguments get displayed nicely in console:

```
if (window.console && console.log) {
    // only call console[].apply for browsers that support it, fallback to console.log
    try {
        console['log'].apply(console, args);
    } catch (e) {
        console.log(args);
    }
}
```

**Comment by camsjams** [comment]
I made a PR instead:
https://github.com/rafde/PrioritizedSubPub/pull/3

**Comment by rafde** [comment]
Sorry, documentation took me some time. I push a fix but I haven't tested it in IE8. I will try to make some time tomorrow.

**Comment by rafde** [comment]
https://github.com/rafde/PrioritizedSubPub/commit/08aa3019f462f000fc774f0f648c956133b197a7#diff-172ca915034fa03da706a98cb52c7647R261

Fixed and verified using IE7 Window VM.
